//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вода.
    /// </summary>
    // *** Start programmer edit section *** (Вода CustomAttributes)

    // *** End programmer edit section *** (Вода CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВодаE", new string[] {
            "Вода as \'Вода\'"})]
    [View("ВодаL", new string[] {
            "Вода as \'Вода\'"})]
    public class Вода : ICSSoft.STORMNET.DataObject
    {
        
        private int fВода;
        
        // *** Start programmer edit section *** (Вода CustomMembers)

        // *** End programmer edit section *** (Вода CustomMembers)

        
        /// <summary>
        /// Вода.
        /// </summary>
        // *** Start programmer edit section *** (Вода.Вода CustomAttributes)

        // *** End programmer edit section *** (Вода.Вода CustomAttributes)
        public virtual int Вода
        {
            get
            {
                // *** Start programmer edit section *** (Вода.Вода Get start)

                // *** End programmer edit section *** (Вода.Вода Get start)
                int result = this.fВода;
                // *** Start programmer edit section *** (Вода.Вода Get end)

                // *** End programmer edit section *** (Вода.Вода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Вода.Вода Set start)

                // *** End programmer edit section *** (Вода.Вода Set start)
                this.fВода = value;
                // *** Start programmer edit section *** (Вода.Вода Set end)

                // *** End programmer edit section *** (Вода.Вода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВодаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВодаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВодаE", typeof(IIS.Kursovaya_10.Вода));
                }
            }
            
            /// <summary>
            /// "ВодаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВодаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВодаL", typeof(IIS.Kursovaya_10.Вода));
                }
            }
        }
    }
}
