//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Время.
    /// </summary>
    // *** Start programmer edit section *** (Время CustomAttributes)

    // *** End programmer edit section *** (Время CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВремяE", new string[] {
            "Время as \'Время\'"})]
    [View("ВремяL", new string[] {
            "Время as \'Время\'"})]
    public class Время : ICSSoft.STORMNET.DataObject
    {
        
        private int fВремя;
        
        // *** Start programmer edit section *** (Время CustomMembers)

        // *** End programmer edit section *** (Время CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Время.Время CustomAttributes)

        // *** End programmer edit section *** (Время.Время CustomAttributes)
        public virtual int Время
        {
            get
            {
                // *** Start programmer edit section *** (Время.Время Get start)

                // *** End programmer edit section *** (Время.Время Get start)
                int result = this.fВремя;
                // *** Start programmer edit section *** (Время.Время Get end)

                // *** End programmer edit section *** (Время.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Время.Время Set start)

                // *** End programmer edit section *** (Время.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Время.Время Set end)

                // *** End programmer edit section *** (Время.Время Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВремяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВремяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВремяE", typeof(IIS.Kursovaya_10.Время));
                }
            }
            
            /// <summary>
            /// "ВремяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВремяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВремяL", typeof(IIS.Kursovaya_10.Время));
                }
            }
        }
    }
}
