//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кондер.
    /// </summary>
    // *** Start programmer edit section *** (Кондер CustomAttributes)

    // *** End programmer edit section *** (Кондер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КондерE", new string[] {
            "Кондицион as \'Кондицион\'"})]
    [View("КондерL", new string[] {
            "Кондицион as \'Кондицион\'"})]
    public class Кондер : ICSSoft.STORMNET.DataObject
    {
        
        private int fКондицион;
        
        // *** Start programmer edit section *** (Кондер CustomMembers)

        // *** End programmer edit section *** (Кондер CustomMembers)

        
        /// <summary>
        /// Кондицион.
        /// </summary>
        // *** Start programmer edit section *** (Кондер.Кондицион CustomAttributes)

        // *** End programmer edit section *** (Кондер.Кондицион CustomAttributes)
        public virtual int Кондицион
        {
            get
            {
                // *** Start programmer edit section *** (Кондер.Кондицион Get start)

                // *** End programmer edit section *** (Кондер.Кондицион Get start)
                int result = this.fКондицион;
                // *** Start programmer edit section *** (Кондер.Кондицион Get end)

                // *** End programmer edit section *** (Кондер.Кондицион Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кондер.Кондицион Set start)

                // *** End programmer edit section *** (Кондер.Кондицион Set start)
                this.fКондицион = value;
                // *** Start programmer edit section *** (Кондер.Кондицион Set end)

                // *** End programmer edit section *** (Кондер.Кондицион Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КондерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КондерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КондерE", typeof(IIS.Kursovaya_10.Кондер));
                }
            }
            
            /// <summary>
            /// "КондерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КондерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КондерL", typeof(IIS.Kursovaya_10.Кондер));
                }
            }
        }
    }
}
