//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Код ошибки.
    /// </summary>
    // *** Start programmer edit section *** (КодОшибки CustomAttributes)

    // *** End programmer edit section *** (КодОшибки CustomAttributes)
    public enum КодОшибки
    {
        
        // *** Start programmer edit section *** (КодОшибки.НетСвета CustomAttributes)

        // *** End programmer edit section *** (КодОшибки.НетСвета CustomAttributes)
        [Caption("НетСвета")]
        НетСвета,
        
        // *** Start programmer edit section *** (КодОшибки.НетСредства CustomAttributes)

        // *** End programmer edit section *** (КодОшибки.НетСредства CustomAttributes)
        [Caption("НетСредства")]
        НетСредства,
        
        // *** Start programmer edit section *** (КодОшибки.НетВоды CustomAttributes)

        // *** End programmer edit section *** (КодОшибки.НетВоды CustomAttributes)
        [Caption("НетВоды")]
        НетВоды,
    }
}
