//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет.
    /// </summary>
    // *** Start programmer edit section *** (Отчет CustomAttributes)

    // *** End programmer edit section *** (Отчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетE", new string[] {
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("ОтчетE", "ТчПрограм", "ТчПрограмE", true, "", "Тч програм", true, new string[] {
            ""})]
    [View("ОтчетL", new string[] {
            "Дата as \'Дата\'"})]
    public class Отчет : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Kursovaya_10.DetailArrayOfТчПрограм fТчПрограм;
        
        // *** Start programmer edit section *** (Отчет CustomMembers)

        // *** End programmer edit section *** (Отчет CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.Дата CustomAttributes)

        // *** End programmer edit section *** (Отчет.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.Дата Get start)

                // *** End programmer edit section *** (Отчет.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Отчет.Дата Get end)

                // *** End programmer edit section *** (Отчет.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.Дата Set start)

                // *** End programmer edit section *** (Отчет.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Отчет.Дата Set end)

                // *** End programmer edit section *** (Отчет.Дата Set end)
            }
        }
        
        /// <summary>
        /// Отчет.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.ТчПрограм CustomAttributes)

        // *** End programmer edit section *** (Отчет.ТчПрограм CustomAttributes)
        public virtual IIS.Kursovaya_10.DetailArrayOfТчПрограм ТчПрограм
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.ТчПрограм Get start)

                // *** End programmer edit section *** (Отчет.ТчПрограм Get start)
                if ((this.fТчПрограм == null))
                {
                    this.fТчПрограм = new IIS.Kursovaya_10.DetailArrayOfТчПрограм(this);
                }
                IIS.Kursovaya_10.DetailArrayOfТчПрограм result = this.fТчПрограм;
                // *** Start programmer edit section *** (Отчет.ТчПрограм Get end)

                // *** End programmer edit section *** (Отчет.ТчПрограм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.ТчПрограм Set start)

                // *** End programmer edit section *** (Отчет.ТчПрограм Set start)
                this.fТчПрограм = value;
                // *** Start programmer edit section *** (Отчет.ТчПрограм Set end)

                // *** End programmer edit section *** (Отчет.ТчПрограм Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетE", typeof(IIS.Kursovaya_10.Отчет));
                }
            }
            
            /// <summary>
            /// "ОтчетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетL", typeof(IIS.Kursovaya_10.Отчет));
                }
            }
        }
    }
}
