//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сбои.
    /// </summary>
    // *** Start programmer edit section *** (Сбои CustomAttributes)

    // *** End programmer edit section *** (Сбои CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СбоиE", new string[] {
            "Время as \'Время\'",
            "Ошибка as \'Ошибка\'"})]
    [View("СбоиL", new string[] {
            "Время as \'Время\'",
            "Ошибка as \'Ошибка\'"})]
    public class Сбои : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fВремя = System.DateTime.Now;
        
        private IIS.Kursovaya_10.КодОшибки fОшибка;
        
        // *** Start programmer edit section *** (Сбои CustomMembers)

        // *** End programmer edit section *** (Сбои CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Сбои.Время CustomAttributes)

        // *** End programmer edit section *** (Сбои.Время CustomAttributes)
        public virtual System.DateTime Время
        {
            get
            {
                // *** Start programmer edit section *** (Сбои.Время Get start)

                // *** End programmer edit section *** (Сбои.Время Get start)
                System.DateTime result = this.fВремя;
                // *** Start programmer edit section *** (Сбои.Время Get end)

                // *** End programmer edit section *** (Сбои.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сбои.Время Set start)

                // *** End programmer edit section *** (Сбои.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Сбои.Время Set end)

                // *** End programmer edit section *** (Сбои.Время Set end)
            }
        }
        
        /// <summary>
        /// Ошибка.
        /// </summary>
        // *** Start programmer edit section *** (Сбои.Ошибка CustomAttributes)

        // *** End programmer edit section *** (Сбои.Ошибка CustomAttributes)
        public virtual IIS.Kursovaya_10.КодОшибки Ошибка
        {
            get
            {
                // *** Start programmer edit section *** (Сбои.Ошибка Get start)

                // *** End programmer edit section *** (Сбои.Ошибка Get start)
                IIS.Kursovaya_10.КодОшибки result = this.fОшибка;
                // *** Start programmer edit section *** (Сбои.Ошибка Get end)

                // *** End programmer edit section *** (Сбои.Ошибка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сбои.Ошибка Set start)

                // *** End programmer edit section *** (Сбои.Ошибка Set start)
                this.fОшибка = value;
                // *** Start programmer edit section *** (Сбои.Ошибка Set end)

                // *** End programmer edit section *** (Сбои.Ошибка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СбоиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СбоиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СбоиE", typeof(IIS.Kursovaya_10.Сбои));
                }
            }
            
            /// <summary>
            /// "СбоиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СбоиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СбоиL", typeof(IIS.Kursovaya_10.Сбои));
                }
            }
        }
    }
}
