//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список програм.
    /// </summary>
    // *** Start programmer edit section *** (СписокПрограм CustomAttributes)

    // *** End programmer edit section *** (СписокПрограм CustomAttributes)
    [AutoAltered()]
    [Caption("Список програм")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокПрограмE", new string[] {
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("СписокПрограмE", "ТчПрограм", "ТчПрограмE", true, "", "Тч програм", true, new string[] {
            ""})]
    [View("СписокПрограмL", new string[] {
            "Дата as \'Дата\'"})]
    public class СписокПрограм : IIS.Kursovaya_10.Отчет
    {
        
        // *** Start programmer edit section *** (СписокПрограм CustomMembers)

        // *** End programmer edit section *** (СписокПрограм CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (СписокПрограм.Дата CustomAttributes)

        // *** End programmer edit section *** (СписокПрограм.Дата CustomAttributes)
        public override System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (СписокПрограм.Дата Get start)

                // *** End programmer edit section *** (СписокПрограм.Дата Get start)
                System.DateTime result = base.Дата;
                // *** Start programmer edit section *** (СписокПрограм.Дата Get end)

                // *** End programmer edit section *** (СписокПрограм.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СписокПрограм.Дата Set start)

                // *** End programmer edit section *** (СписокПрограм.Дата Set start)
                base.Дата = value;
                // *** Start programmer edit section *** (СписокПрограм.Дата Set end)

                // *** End programmer edit section *** (СписокПрограм.Дата Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокПрограмE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокПрограмE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокПрограмE", typeof(IIS.Kursovaya_10.СписокПрограм));
                }
            }
            
            /// <summary>
            /// "СписокПрограмL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокПрограмL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокПрограмL", typeof(IIS.Kursovaya_10.СписокПрограм));
                }
            }
        }
    }
}
