//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч програм.
    /// </summary>
    // *** Start programmer edit section *** (ТчПрограм CustomAttributes)

    // *** End programmer edit section *** (ТчПрограм CustomAttributes)
    [AutoAltered()]
    [Caption("Тч програм")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчПрограмE", new string[] {
            "Режим as \'Режим\'",
            "Режим.Название as \'Название\'",
            "Режим.Вода.Вода as \'Вода\'",
            "Режим.Время.Время as \'Время\'",
            "Режим.Кондер.Кондицион as \'Кондицион\'",
            "Режим.МоющееСред.Моющее as \'Моющее\'",
            "Режим.температуры.Температура as \'Температура\'"}, Hidden=new string[] {
            "Режим.Название"})]
    [MasterViewDefineAttribute("ТчПрограмE", "Режим", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class ТчПрограм : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Kursovaya_10.Режим fРежим;
        
        private IIS.Kursovaya_10.Отчет fОтчет;
        
        // *** Start programmer edit section *** (ТчПрограм CustomMembers)

        // *** End programmer edit section *** (ТчПрограм CustomMembers)

        
        /// <summary>
        /// Тч програм.
        /// </summary>
        // *** Start programmer edit section *** (ТчПрограм.Режим CustomAttributes)

        // *** End programmer edit section *** (ТчПрограм.Режим CustomAttributes)
        [PropertyStorage(new string[] {
                "Режим"})]
        [NotNull()]
        public virtual IIS.Kursovaya_10.Режим Режим
        {
            get
            {
                // *** Start programmer edit section *** (ТчПрограм.Режим Get start)

                // *** End programmer edit section *** (ТчПрограм.Режим Get start)
                IIS.Kursovaya_10.Режим result = this.fРежим;
                // *** Start programmer edit section *** (ТчПрограм.Режим Get end)

                // *** End programmer edit section *** (ТчПрограм.Режим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчПрограм.Режим Set start)

                // *** End programmer edit section *** (ТчПрограм.Режим Set start)
                this.fРежим = value;
                // *** Start programmer edit section *** (ТчПрограм.Режим Set end)

                // *** End programmer edit section *** (ТчПрограм.Режим Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya_10.Отчет.
        /// </summary>
        // *** Start programmer edit section *** (ТчПрограм.Отчет CustomAttributes)

        // *** End programmer edit section *** (ТчПрограм.Отчет CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage("Отчет")]
        [TypeUsage(new string[] {
                "IIS.Kursovaya_10.Отчет",
                "IIS.Kursovaya_10.СписокПрограм"})]
        public virtual IIS.Kursovaya_10.Отчет Отчет
        {
            get
            {
                // *** Start programmer edit section *** (ТчПрограм.Отчет Get start)

                // *** End programmer edit section *** (ТчПрограм.Отчет Get start)
                IIS.Kursovaya_10.Отчет result = this.fОтчет;
                // *** Start programmer edit section *** (ТчПрограм.Отчет Get end)

                // *** End programmer edit section *** (ТчПрограм.Отчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчПрограм.Отчет Set start)

                // *** End programmer edit section *** (ТчПрограм.Отчет Set start)
                this.fОтчет = value;
                // *** Start programmer edit section *** (ТчПрограм.Отчет Set end)

                // *** End programmer edit section *** (ТчПрограм.Отчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчПрограмE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчПрограмE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчПрограмE", typeof(IIS.Kursovaya_10.ТчПрограм));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчПрограм.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчПрограм CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчПрограм CustomAttributes)
    public class DetailArrayOfТчПрограм : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya_10.DetailArrayOfТчПрограм members)

        // *** End programmer edit section *** (IIS.Kursovaya_10.DetailArrayOfТчПрограм members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчПрограм by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчПрограм.
        /// </summary>
        public DetailArrayOfТчПрограм(IIS.Kursovaya_10.Отчет fОтчет) : 
                base(typeof(ТчПрограм), ((ICSSoft.STORMNET.DataObject)(fОтчет)))
        {
        }
        
        public IIS.Kursovaya_10.ТчПрограм this[int index]
        {
            get
            {
                return ((IIS.Kursovaya_10.ТчПрограм)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya_10.ТчПрограм dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
